### ISSUE TITLE
[BUG] DESIGN ISSUE ON INDEX FILE

### ISSUE THREAD

**Issue by sb39** [zero-to-mastery/Halloween-Hacktoberfest#100]
1.  Back to top button is not there is not visible

2. Navbar background goes invisible from 0-50px

**Comment by sb39** [comment]
@MattCSmith  how to load scripts in your dynamic loader , means I simply want to migrate code from index.js to headfoot.js in that format

**Comment by MattCSmith** [comment]
@sb39 For global JS add it to the global.js file

For page specific scripts add them to the page in the section commented :)

**Comment by MattCSmith** [comment]
1. I noticed the back to top was broken, while I was working on the dynamic loader. Although I couldn't find the issue and ran out of time last night

2. I think that was an intentional design idea someone had. So as there is code to make it opaque on scroll.

**Comment by MattCSmith** [comment]
Closing as this bug seems to have been addressed
