### ISSUE TITLE
readFile function not able to load files

### ISSUE THREAD

**Issue by hmahajan99** [zero-to-mastery/Halloween-Hacktoberfest#20]
the readFile function in names.js and facts.js is not able to load the text file hence the New Name and New Facts buttons do not work. The solution is most likely to use http:// protocol instead of file:// but I can't figure out how . (https://stackoverflow.com/questions/28922881/error-failed-to-execute-send-on-xmlhttprequest-failed-to-load-file-ang)

**Comment by bbtora** [comment]
New name and new facts buttons work just fine for me.

**Comment by hmahajan99** [comment]
The dont seem to be working for me ! Getting a cors error.
