### ISSUE TITLE
Facts page button does not work

### ISSUE THREAD

**Issue by OhSnapdragon** [zero-to-mastery/Halloween-Hacktoberfest#205]
The button and the mouse pointer change when hovering over it, but clicking it does nothing.

![thisbutton](https://user-images.githubusercontent.com/43509217/46899910-e0024a80-ce67-11e8-850b-2f6fbf3a7826.PNG)

**Comment by The24thDS** [comment]
Can we close this issue now? It has been fixed @SamirJouni
