### ISSUE TITLE
Recipes Link on Navbar

### ISSUE THREAD

**Issue by sanjithpk** [zero-to-mastery/Halloween-Hacktoberfest#27]
The recipes link on navbar doesnt have a link attached to it.

**Comment by sb39** [comment]
i think you can generate random content in it

**Comment by joshbmartin** [comment]
I have the recipes link pointing to a new recipes page in the open PR. Please check it out :)

**Comment by MattCSmith** [comment]
The PR has been merged, however the problem still persists on other pages. 
Each page has its own Navbar instance, so links need added or updating on each page.
So there is an opportunity for someone that wants another PR to make the change :)
