### ISSUE TITLE
branch behind of commits

### ISSUE THREAD

**Issue by sb39** [zero-to-mastery/Halloween-Hacktoberfest#35]
hello @MattCSmith, how to update my master branch with this repo's last commit.

**Comment by MattCSmith** [comment]
Hey @sb39,
You need to sync your fork with the upstream repo. You can find out more information on this here:
https://help.github.com/articles/syncing-a-fork/

Let me know if you need any help
Regards
Matt

**Comment by sb39** [comment]
@MattCSmith ,I dont knw why my repo is showing to be ahead of the original branch. How to bring it back to master

**Comment by sb39** [comment]
@MattCSmith your discord is pls

**Comment by MattCSmith** [comment]
@mattchow#8280

**Comment by sb39** [comment]
> @mattchow#8280

add me sb39#9199
