### ISSUE TITLE
pumpkin designs page

### ISSUE THREAD

**Issue by sb39** [zero-to-mastery/Halloween-Hacktoberfest#41]
page missing contents

**Comment by MattCSmith** [comment]
Page content has now been added. However there are still lots of improvements that could be made, a few could be:

- Display each design in a Bootstrap card

- Catergorise designs

- Search designs

**Comment by jeremyfox36** [comment]
Hi - I'd like take on the first one in your list (the bootstrap cards).  Is that ok?

**Comment by manisha-A** [comment]
Hi - I have created a PR for handling the search designs. https://github.com/zero-to-mastery/Halloween-Hacktoberfest/pull/234

**Comment by thisisabdus** [comment]
@jeremyfox36, go ahead and do it! Good Luck.
