### ISSUE TITLE
[FEATURE WANTED] removing nav-links colour

### ISSUE THREAD

**Issue by sb39** [zero-to-mastery/Halloween-Hacktoberfest#59]
removing nav-links colour once one link is already active

**Comment by sb39** [comment]
@MattCSmith yup , you got that accurate :1st_place_medal:

**Comment by MattCSmith** [comment]
Cool, thats a good starter issue for someone. Requires the changing of one line in the styles.css file.

**Comment by sb39** [comment]
@MattCSmith @bbtora  the page on first load doesnot show Home button to be active
