### ISSUE TITLE
Some pages have JS files being imported in both the head and body

### ISSUE THREAD

**Issue by zach-caldwell** [zero-to-mastery/Halloween-Hacktoberfest#88]
These should not be duplicated and should be at the end of the `body` and not the `head` across all pages.

**Comment by sb39** [comment]
@zach-caldwell  you can remove and make a PR , thanks for noticing :1st_place_medal:

**Comment by MattCSmith** [comment]
Closing as this should have been resolved in:
https://github.com/zero-to-mastery/Halloween-Hacktoberfest/pull/94
